baseURL = "https://nomaster.cc/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Mic Szillat"

[blackfriday]
extensions = ["hardLineBreak"]

[permalinks]
fixed = ":title/"
posts = "posts/:slug/"

[params]
author = "Mic Szillat"
description = "nomaster"
bio = "Systems Engineer.\nIT Automation Consultant."
avatar = "img/avatar.jpg"
favicon = "img/favicon.ico"

	[params.contact]
    email = "mic@nomaster.cc"
    github = "nomaster"
    instagram = "micnomaster"
    twitter = "nomaster"
    ello = ""


