baseURL = "https://nomaster.cc/"
buildDrafts = false
buildFuture = false
buildExpired = false
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Mic Szillat"

[blackfriday]
extensions = ["hardLineBreak"]

[permalinks]
fixed = ":title/"
posts = "posts/:slug/"

[params]
author = "Mic Szillat"
description = "nomaster"
bio = "nomaster\nIT systems engineer and consultant"
avatar = "img/avatar.jpg"
favicon = "img/favicon.ico"
email = "mic@nomaster.cc"
error404 = "ceci n'est pas une pipe"

[params.contact]
github = "https://github.com/nomaster"
instagram = "https://www.instagram.com/micnomaster/"
twitter = "https://twitter.com/nomaster"
linkedin = "https://www.linkedin.com/in/mic-szillat-75a4ba127/"
youtube = "https://www.youtube.com/channel/UCDkyI271KISc3G222wbU90g"
xing = "https://www.xing.com/profile/Micoto_Szillat/cv"
